trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux-based agent, or change to 'windows-latest' if needed

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libdbus-glib-1-2 google-chrome-stable
    displayName: 'Install Chrome dependencies'

  - script: |
      pip install --upgrade webdriver-manager
    displayName: 'Install webdriver-manager'

  - script: |
      rm -rf ~/.wdm  # Clear any cached drivers
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "ChromeDriver Path: $(which chromedriver)"
    displayName: 'Verify ChromeDriver Path'

  - script: |
      python -m pytest tests/test_update.py
    displayName: 'Run Tests'
