trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image for the pipeline

variables:
  pythonVersion: '3.x'  # Specify the Python version to use
  bugType: 'Bug'  # Set the work item type (Bug)

steps:
  # Install the specified Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true

  # Install Google Chrome on the Ubuntu agent
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Google Chrome'

  # Install dependencies from requirements.txt
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Run the Selenium tests with pytest
  - script: |
      pytest test_update.py --maxfail=1 --disable-warnings -q > test_results.log 2>&1
      echo $? > pytest_exit_code.txt
    displayName: 'Run Selenium Tests'

  # Check the test results and create a bug if tests failed
  - script: |
      if [ $(cat pytest_exit_code.txt) -ne 0 ]; then
        echo "Tests failed. Creating a bug in Azure DevOps..."
        az devops login --organization https://dev.azure.com/SignaTechServicesIndia --token A0us9bS1c6qe5bub6CT5FGRR4JcmPDg7uadVFmw4D65bvtdPcBVdJQQJ99AKACAAAAAPnX9AAAASAZDO4GFB
        az boards work-item create --title "Automated Bug: Selenium Test Failure" --type $(bugType) --description "Selenium tests failed. See test_results.log for details." --project "SignaDart"
      else
        echo "Tests passed. No bug created."
      fi
    displayName: 'Create Bug on Test Failure'
