trigger:
- main  # Trigger the pipeline on changes to the main branch (adjust based on your branch)

pool:
  vmImage: 'ubuntu-latest'  # Use a suitable VM image for your pipeline (you can also use 'windows-latest' if needed)

variables:
  pythonVersion: '3.x'  # Specify the Python version to use (3.x version will auto install the latest)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)  # Select Python version to install
    addToPath: true  # Adds Python to the system PATH

- script: |
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable  # Install Chrome on Ubuntu
  displayName: 'Install Google Chrome'

- script: |
    python -m pip install --upgrade pip  # Upgrade pip to the latest version
    pip install -r requirements.txt  # Install dependencies from the requirements.txt file
  displayName: 'Install dependencies'

- script: |
    pytest test_update.py --maxfail=1 --disable-warnings -q  # Run the pytest script
  displayName: 'Run Selenium Tests'
