trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Ensure the repository is checked out

  - script: |
      pwd  # Print current working directory
      ls -R  # List files recursively to check for file locations
    displayName: 'List Files in Current Directory'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libdbus-glib-1-2 google-chrome-stable
    displayName: 'Install Chrome dependencies'

  - script: |
      pip install --upgrade webdriver-manager
    displayName: 'Install webdriver-manager'

  - script: |
      rm -rf ~/.wdm  # Clear any cached drivers
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pytest test_update.py  # Run pytest directly from the root directory
    displayName: 'Run Tests'
