trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image for the pipeline

steps:
  # Install the specified Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install Google Chrome on the Ubuntu agent
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Google Chrome'

  # Install dependencies from requirements.txt
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Run the Selenium tests with pytest
  - script: |
      pytest test_update.py --maxfail=1 --disable-warnings -q > test_results.log 2>&1
      exitCode=$?
      echo $exitCode > pytest_exit_code.txt
      if [ $exitCode -ne 0 ]; then
        echo "Tests failed, creating a bug in Azure DevOps..."
        
        # Hardcode the bug URL with the correct organization and project
        bugUrl="https://dev.azure.com/SignaTechServicesIndia/SignaDart/_apis/wit/workitems/Bug?api-version=7.1-preview.2"
        
        # Prepare the bug data (you can modify this data according to your requirements)
        bugData='{
          "fields": {
            "System.Title": "Automated Bug: Selenium Test Failure",
            "System.Description": "Automated bug created due to test failures in Selenium tests."
          }
        }'

        # Create a bug in Azure DevOps if tests fail
        curl -u :$pat \
          -X POST \
          -H "Content-Type: application/json" \
          -d "$bugData" \
          "$bugUrl"
      fi
    displayName: 'Run Selenium Tests and Create Bug if Failed'
