trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image for the pipeline

variables:
  pythonVersion: '3.x'  # Specify the Python version to use
  bugType: 'Bug'  # Set the work item type to 'Bug'

steps:
  # Use the specified Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true
    displayName: 'Set up Python'

  # Install Google Chrome
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Google Chrome'

  # Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Run Selenium tests with pytest
  - script: |
      pytest test_update.py --maxfail=1 --disable-warnings -q > test_results.log 2>&1
      echo $? > pytest_exit_code.txt
    displayName: 'Run Selenium Tests'

  # Debug variable resolution (optional for troubleshooting)
  - script: |
      echo "Debugging Variable Resolution"
      echo "Bug type: $(bugType)"
      echo "URL: https://dev.azure.com/SignaTechServicesIndia/SignaDart/_apis/wit/workitems/$(bugType)?api-version=6.0"
    displayName: 'Debug Variable Resolution'

  # Check test results and raise a bug if tests fail
    - script: |
      exit_code=$(cat pytest_exit_code.txt)
      if [ $exit_code -ne 0 ]; then
        echo "Tests failed. Creating a bug in Azure DevOps..."

        # Read the test results log and escape special characters
        log_output=$(cat test_results.log | sed 's/"/\\"/g')

        # Use Azure DevOps API to create a bug
        curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AZURE_DEVOPS_PAT" \
          --data "{
            \"fields\": {
              \"System.Title\": \"Automated Test Failure: Selenium Tests\",
              \"System.Description\": \"The Selenium tests failed during the pipeline execution. Please investigate the issue.\\n\\nLog output:\\n$log_output\",
              \"System.Tags\": \"Automated; Bug\"
            }
          }" \
          "https://dev.azure.com/SignaTechServicesIndia/SignaDart/_apis/wit/workitems/$Bug?api-version=6.0"

        exit $exit_code
      else
        echo "All tests passed successfully."
      fi
    displayName: 'Check Test Results and Raise Bug'
    env:
      AZURE_DEVOPS_PAT: $(azureDevOpsPAT)
