trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a hosted Ubuntu agent

steps:
# Step 1: Set up Python environment
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the latest Python 3.x version
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # Assuming you have a requirements.txt file that includes dependencies like selenium, pytest, etc.
    pip install webdriver-manager  # Install WebDriver manager for handling ChromeDriver
  displayName: 'Install Dependencies'

# Step 3: Run the Selenium tests with pytest
- script: |
    pytest test_update.py  # Replace with the relative path to your test file
  displayName: 'Run Selenium Tests'

# Step 4: Archive test results (optional, if you want to capture the results)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'  # Assuming you're using pytest with the --junit-xml option to generate XML results
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
