trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image for the pipeline

variables:
  pythonVersion: '3.x'  # Specify the Python version to use
  bugType: 'Bug'  # Set the work item type (Bug)
  azureDevOpsPAT: $(azureDevOpsPAT)  # Personal Access Token stored in pipeline variables
  azureDevOpsOrganization: 'SignaTechServicesIndia'  # Your Azure DevOps organization
  azureDevOpsProject: 'SignaDart'  # Your Azure DevOps project

steps:
  # Install the specified Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true

  # Install Google Chrome on the Ubuntu agent
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Google Chrome'

  # Install dependencies from requirements.txt
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Run the Selenium tests with pytest
  - script: |
      pytest test_update.py --maxfail=1 --disable-warnings -q > test_results.log 2>&1
      echo $? > pytest_exit_code.txt
    displayName: 'Run Selenium Tests'

  # Create a Bug work item in Azure DevOps if tests fail
  - script: |
      exitCode=$(cat pytest_exit_code.txt)
      if [ $exitCode -ne 0 ]; then
        echo "Tests failed, creating a bug in Azure DevOps..."

        # Prepare the bug creation request
        bugData='{
          "fields": {
            "System.Title": "Automated Bug: Selenium Tests Failed",
            "System.Description": "Selenium tests failed during the pipeline run. Please check the logs for more details.",
            "System.WorkItemType": "Bug"
          }
        }'

        # Create the bug work item using Azure DevOps REST API
        curl -u :$(azureDevOpsPAT) \
          -X POST \
          -H "Content-Type: application/json" \
          -d "$bugData" \
          "https://dev.azure.com/$(azureDevOpsOrganization)/$(azureDevOpsProject)/_apis/wit/workitems/$bugType?api-version=7.1-preview.2"
      fi
    displayName: 'Create Bug if Tests Fail'
