trigger:
  branches:
    include:
      - main  # This should be your main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Python environment
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Step 2: Checkout the repository containing your tests
  - checkout: self

  # Step 3: Install dependencies from requirements.txt
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Step 4: List files to ensure test_update.py exists
  - script: |
      echo "Listing files in the current directory:"
      ls -la
    displayName: 'List files in current directory'

  # Step 5: Run the specific test file (test_update.py)
  - script: |
      echo "Running tests with pytest:"
      pytest -v test_update.py || exit 1
    displayName: 'Run Selenium Tests (test_update.py)'

  # Step 6: Check the result log for detailed information
  - script: |
      echo "Displaying result.log content:"
      cat result.log || echo "result.log not found"
    displayName: 'Display result.log'
