trigger:
- main  # Adjust the trigger as per your requirements

pool:
  vmImage: 'ubuntu-latest'  # Choose your desired VM image (ubuntu, windows-latest, etc.)

variables:
  organization: 'SignaTechServicesIndia'  # Your Azure DevOps organization
  project: 'SignaDart'  # Your Azure DevOps project
  bugType: 'Bug'  # Work item type, e.g., Bug
  apiVersion: '7.1-preview.2'  # API version

stages:
- stage: RunSeleniumAndCreateBug
  jobs:
  - job: RunTestsAndCreateBug
    steps:
    - task: UsePythonVersion@0  # Example task for setting up Python, remove if not needed
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        echo "Running Selenium Tests..."
        # Add the command to run your Selenium tests here
        # If tests fail, the script will proceed to create a bug

        testResult="failed"  # Simulate test result (replace with actual test result logic)

        if [ "$testResult" == "failed" ]; then
          echo "Tests failed, creating a bug in Azure DevOps..."
          
          # Dynamically construct the URL with variables
          bugUrl="https://dev.azure.com/$(organization)/$(project)/_apis/wit/workitems/$(bugType)?api-version=$(apiVersion)"

          echo "Bug creation URL: $bugUrl"

          # Example of creating a bug using curl (replace with actual bug creation logic)
          bugData='{
            "fields": {
              "System.Title": "Automated Bug: Selenium Test Failure",
              "System.Description": "Automated bug created due to test failures in Selenium tests."
            }
          }'
          
          # Use curl to create the bug
          curl -u :$(System.AccessToken) \
            -X POST \
            -H "Content-Type: application/json-patch+json" \
            -d "$bugData" \
            "$bugUrl"
        else
          echo "Tests passed successfully!"
        fi
      displayName: 'Run Selenium Tests and Create Bug if Failed'

    - script: |
        echo "Bug URL using placeholders: https://dev.azure.com/$(organization)/$(project)/_apis/wit/workitems/$(bugType)?api-version=$(apiVersion)"
      displayName: 'Display the Bug URL'
