trigger:
  branches:
    include:
      - main  # Adjust this to match your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Python environment
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Step 2: Checkout the repository
  - checkout: self

  # Step 3: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Step 4: Run the specific test file (test_update.py)
  - script: |
      pytest -v test_update.py > result.log || exit 1
    displayName: 'Run Selenium Tests (test_update.py)'

  # Step 5: Display result.log to diagnose failures
  - script: |
      cat result.log
    displayName: 'Display result.log'
