trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image for the pipeline

variables:
  pythonVersion: '3.x'  # Specify the Python version to use
  bugType: 'Bug'  # Set the work item type (Bug)
  # These variables are assumed to be set as pipeline variables (secret) in Azure DevOps UI
  # e.g., azureDevOpsOrganization, azureDevOpsProject, azureDevOpsPAT

steps:
  # Install the specified Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true

  # Install Google Chrome on the Ubuntu agent
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Google Chrome'

  # Install dependencies from requirements.txt
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Run the Selenium tests with pytest
  - script: |
      pytest test_update.py --maxfail=1 --disable-warnings -q > test_results.log 2>&1
      exitCode=$?
      echo $exitCode > pytest_exit_code.txt
      if [ $exitCode -ne 0 ]; then
        echo "Tests failed, creating a bug in Azure DevOps..."
        
        # Prepare the bug data (you can modify this data according to your requirements)
        bugData='{
          "fields": {
            "System.Title": "Automated Bug: Selenium Test Failure",
            "System.Description": "Automated bug created due to test failures.",
            "System.AssignedTo": {
              "id": "your-user-id"  # Optional: Set a user ID if you want to assign the bug
            },
            "System.Tags": "Automated, Selenium Test"
          }
        }'
        
        # Create a bug in Azure DevOps if tests fail
        curl -u :$(azureDevOpsPAT) \
          -X POST \
          -H "Content-Type: application/json" \
          -d "$bugData" \
          "https://dev.azure.com/$(azureDevOpsOrganization)/$(azureDevOpsProject)/_apis/wit/workitems/$(bugType)?api-version=7.1-preview.2"
      fi
    displayName: 'Run Selenium Tests and Create Bug if Failed'
